### ISSUE TITLE
Too many iteration (Maybe never stopping) case

### ISSUE THREAD

**Issue by tink-expo** [ehdkacjswo/CS453_team2_project#2]
```
def g(x):
    for _ in range(x):
        pass
    else:
        pass

    while x < 5:
        x += 1
    else:
        if x > 10:
            if x < 12:
                pass
        else:
            pass
```

This function was easily covered with simple AVM search.
However, in current implementation it takes more than 800 iteration (Stopped here by keyboardinterrupt, not sure if it ends)

**Comment by ehdkacjswo** [comment]
Mutation was applied onto original test case too on single input case. Resolved.
